### ISSUE TITLE
cannot locate data files

### ISSUE THREAD

**Issue by zheyizhu** [zorazrw/nqt-retrieval#2]
[dpr.data.biencoder_data][ERROR] - cannot locate data files in name /mnt/zhiruow/hitab/table-retrieval/datasets/nq_table/tables_proc.jsonl

**Comment by zorazrw** [comment]
Hi, while you should have the processed `table_proc.jsonl` (or any other name) using [this script](https://github.com/zorazrw/nqt-retrieval/blob/master/process_table.py), you could resolve this data file issue by either method below:
(1) specify value for argument as `conf.ctx_sources=${your_json_file}`
(2) change the paths in [this file](https://github.com/zorazrw/nqt-retrieval/blob/master/conf/ctx_sources/table_sources.yaml) to where you store jsonl file.

**Comment by zheyizhu** [comment]
Where to find original data files?

**Comment by zorazrw** [comment]
You can find the original table files in the DTR repository [here](https://github.com/google-research/tapas/blob/master/DENSE_TABLE_RETRIEVER.md).
